name: CI

on:
  push:
    tags:
      - BUILD-*

jobs:
  mac-job:
    runs-on: macos-12
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - run: ./build.sh
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            *.so
